### ISSUE TITLE
Can not reproduce the experiment result 

### ISSUE THREAD

**Issue by HaoYang-219** [Ahmadreza-Jeddi/Learn2Perturb#1]
Hello,  When I implement your github code,  first It makes a mistake the  division is zero, I think the mistake is caused by 
for i in range(1, epoch - args.noise_add_delay +1):
harmonic += 1 / i when epoch=args.noise_add_delay, so I modify it to  harmonic += 1 / (i+1), and then it makes  a mistake when evaluate:
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn. I think it is because the code with torch.no_grad(): which does not need to compute gradient but when you run pgd attack: perturbed_image = pgd(model, inputs, labels, epsilon = epsilon) which will use gradient message,  I don't know you how to deal with this mistake. I delete with torch.no_grad(): , and then the model  can work, however, the experiment result is less than your paper about 8%, and a confused  thing is that why you write model.train() in your pgd attack code, which will effect the experiment result actually, it bothered me for days. 
Hopes for your reply.

**Comment by Fly2flies** [comment]
> Hello, When I implement your github code, first It makes a mistake the division is zero, I think the mistake is caused by
> for i in range(1, epoch - args.noise_add_delay +1):
> harmonic += 1 / i when epoch=args.noise_add_delay, so I modify it to harmonic += 1 / (i+1), and then it makes a mistake when evaluate:
> RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn. I think it is because the code with torch.no_grad(): which does not need to compute gradient but when you run pgd attack: perturbed_image = pgd(model, inputs, labels, epsilon = epsilon) which will use gradient message, I don't know you how to deal with this mistake. I delete with torch.no_grad(): , and then the model can work, however, the experiment result is less than your paper about 8%, and a confused thing is that why you write model.train() in your pgd attack code, which will effect the experiment result actually, it bothered me for days.
> Hopes for your reply.

Hello, have you solved the problem?
I found another small error: Torch is not imported in main.py.

**Comment by asthaverma13** [comment]
> Hello, When I implement your github code, first It makes a mistake the division is zero, I think the mistake is caused by for i in range(1, epoch - args.noise_add_delay +1): harmonic += 1 / i when epoch=args.noise_add_delay, so I modify it to harmonic += 1 / (i+1), and then it makes a mistake when evaluate: RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn. I think it is because the code with torch.no_grad(): which does not need to compute gradient but when you run pgd attack: perturbed_image = pgd(model, inputs, labels, epsilon = epsilon) which will use gradient message, I don't know you how to deal with this mistake. I delete with torch.no_grad(): , and then the model can work, however, the experiment result is less than your paper about 8%, and a confused thing is that why you write model.train() in your pgd attack code, which will effect the experiment result actually, it bothered me for days. Hopes for your reply.

Hi, I am getting the same problem.
After removing torch.no_grad() during evaluation (because it is giving error otherwise), I am not able to replicate the results mentioned in the paper and they are coming out to be very less than stated.
If you have solved the problem, please let me know the solution.

Thanks
Astha Verma
PhD Scholar,
IIIT Delhi, India.

**Comment by asthaverma13** [comment]
I am from the Visual Conception Group (VCG) at the Indraprastha Institute of Information Technology (IIITD) Delhi. I was trying to reproduce your paper "Learn2Perturb" using the code provided by you [here](https://github.com/Ahmadreza-Jeddi/Learn2Perturb). 

Unfortunately, I couldn't get the results mentioned in the paper and the difference is significant. For your information, on CIFAR10 + ResNetv1 (20), I am getting an accuracy of 52.13, 28.20, and 31.82 on clean-data, under PGD attack, and under FGSM attack, respectively (rounded to 2 decimal points). Furthermore, for CIFAR100 + ResNetv1 (20), the clean-data accuracy is just 25.57.

Therefore, I would request more information on the implementation details, particularly the parameters and their default values. I have cross-checked with the values provided by you in the paper and have found that the defaults values are just the same. So, any further information in this regard will be highly appreciated. In addition, it would be wonderful if you could provide a pretrained model as well.

Thank you for your time and consideration. I look forward to hearing from you soon.

**Comment by peace-andjoy** [comment]
> I am from the Visual Conception Group (VCG) at the Indraprastha Institute of Information Technology (IIITD) Delhi. I was trying to reproduce your paper "Learn2Perturb" using the code provided by you [here](https://github.com/Ahmadreza-Jeddi/Learn2Perturb).
> 
> Unfortunately, I couldn't get the results mentioned in the paper and the difference is significant. For your information, on CIFAR10 + ResNetv1 (20), I am getting an accuracy of 52.13, 28.20, and 31.82 on clean-data, under PGD attack, and under FGSM attack, respectively (rounded to 2 decimal points). Furthermore, for CIFAR100 + ResNetv1 (20), the clean-data accuracy is just 25.57.
> 
> Therefore, I would request more information on the implementation details, particularly the parameters and their default values. I have cross-checked with the values provided by you in the paper and have found that the defaults values are just the same. So, any further information in this regard will be highly appreciated. In addition, it would be wonderful if you could provide a pretrained model as well.
> 
> Thank you for your time and consideration. I look forward to hearing from you soon.

hello I meet the same question now. Have you solved it? Thank you.
